"""Add Meeting fields and TranscriptSegment model

Revision ID: 4876102672d1
Revises: 2cd075abdb7c
Create Date: 2025-12-29 16:10:33.715014

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4876102672d1'
down_revision: Union[str, None] = '2cd075abdb7c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('transcript_segments',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('meeting_id', sa.String(length=36), nullable=True),
    sa.Column('order', sa.Integer(), nullable=True),
    sa.Column('start_time', sa.Float(), nullable=True),
    sa.Column('end_time', sa.Float(), nullable=True),
    sa.Column('speaker', sa.String(length=50), nullable=True),
    sa.Column('content_raw', sa.Text(), nullable=True),
    sa.Column('content_polished', sa.Text(), nullable=True),
    sa.Column('content_translated', sa.Text(), nullable=True),
    sa.Column('is_final', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['meeting_id'], ['meetings.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_transcript_segments_id'), 'transcript_segments', ['id'], unique=False)
    op.create_index(op.f('ix_transcript_segments_order'), 'transcript_segments', ['order'], unique=False)
    op.add_column('meetings', sa.Column('duration', sa.Float(), nullable=True))
    op.add_column('meetings', sa.Column('audio_url', sa.String(), nullable=True))
    op.add_column('meetings', sa.Column('language', sa.String(length=10), nullable=True))
    op.add_column('meetings', sa.Column('template_name', sa.String(length=50), nullable=True))
    op.add_column('meetings', sa.Column('transcript_raw', sa.Text(), nullable=True))
    op.add_column('meetings', sa.Column('transcript_polished', sa.Text(), nullable=True))
    op.add_column('meetings', sa.Column('summary_json', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('meetings', 'summary_json')
    op.drop_column('meetings', 'transcript_polished')
    op.drop_column('meetings', 'transcript_raw')
    op.drop_column('meetings', 'template_name')
    op.drop_column('meetings', 'language')
    op.drop_column('meetings', 'audio_url')
    op.drop_column('meetings', 'duration')
    op.drop_index(op.f('ix_transcript_segments_order'), table_name='transcript_segments')
    op.drop_index(op.f('ix_transcript_segments_id'), table_name='transcript_segments')
    op.drop_table('transcript_segments')
    # ### end Alembic commands ###
