"""add custom_prompt to meetings and templates

Revision ID: 9fb3cc7a43bb
Revises: 6b1ab324c927
Create Date: 2026-02-25 16:48:20.136980

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9fb3cc7a43bb'
down_revision: Union[str, None] = '6b1ab324c927'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('custom_templates',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('base_template', sa.String(length=50), nullable=False),
    sa.Column('custom_prompt', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_custom_templates_id'), 'custom_templates', ['id'], unique=False)
    op.add_column('meetings', sa.Column('custom_prompt', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    op.drop_column('meetings', 'custom_prompt')
    op.drop_index(op.f('ix_custom_templates_id'), table_name='custom_templates')
    op.drop_table('custom_templates')
    # ### end Alembic commands ###
