# ============================================
# MeetChi Cloud Build - Build & Push Images
# Simplified: Build images only, deploy via Terraform
# ============================================

timeout: '3600s'  # 1 hour timeout

options:
  logging: CLOUD_LOGGING_ONLY
  machineType: 'E2_HIGHCPU_8'

substitutions:
  _REGION: 'asia-southeast1'
  _TAG: 'latest'

steps:
  # ============================================
  # Step 1: Build Backend Image
  # ============================================
  - name: 'gcr.io/cloud-builders/docker'
    id: 'build-backend'
    dir: 'apps/backend'
    args:
      - 'build'
      - '-f'
      - 'Dockerfile'
      - '-t'
      - 'gcr.io/${PROJECT_ID}/meetchi-backend:${_TAG}'
      - '.'

  # ============================================
  # Step 2: Build LLM Service Image (CPU version)
  # ============================================
  - name: 'gcr.io/cloud-builders/docker'
    id: 'build-llm'
    dir: 'apps/llm_service'
    args:
      - 'build'
      - '-f'
      - 'Dockerfile.gpu'
      - '-t'
      - 'gcr.io/${PROJECT_ID}/meetchi-llm-gpu:${_TAG}'
      - '.'
    waitFor: ['-']  # Run in parallel with backend

  # ============================================
  # Step 3: Push Backend Image
  # ============================================
  - name: 'gcr.io/cloud-builders/docker'
    id: 'push-backend'
    args:
      - 'push'
      - 'gcr.io/${PROJECT_ID}/meetchi-backend:${_TAG}'
    waitFor:
      - 'build-backend'

  # ============================================
  # Step 4: Push LLM Image
  # ============================================
  - name: 'gcr.io/cloud-builders/docker'
    id: 'push-llm'
    args:
      - 'push'
      - 'gcr.io/${PROJECT_ID}/meetchi-llm-gpu:${_TAG}'
    waitFor:
      - 'build-llm'

  # ============================================
  # Step 5: List images
  # ============================================
  - name: 'gcr.io/cloud-builders/gcloud'
    id: 'list-images'
    args:
      - 'container'
      - 'images'
      - 'list'
      - '--repository=gcr.io/${PROJECT_ID}'
    waitFor:
      - 'push-backend'
      - 'push-llm'

images:
  - 'gcr.io/${PROJECT_ID}/meetchi-backend:${_TAG}'
  - 'gcr.io/${PROJECT_ID}/meetchi-llm-gpu:${_TAG}'
