apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: meetchi-gpu-asr
  labels:
    deploy-version: v1-breeze-asr
  annotations:
    run.googleapis.com/launch-stage: BETA
spec:
  template:
    metadata:
      annotations:
        run.googleapis.com/cpu-throttling: "false"
        run.googleapis.com/startup-cpu-boost: "true"
        run.googleapis.com/gpu-zonal-redundancy-disabled: "true"
        # Scale to zero when idle — GPU is expensive!
        autoscaling.knative.dev/maxScale: "1"
        autoscaling.knative.dev/minScale: "0"
    spec:
      containerConcurrency: 1
      timeoutSeconds: 1800
      serviceAccountName: meetchi-cloudrun@project-51769b5e-7f0f-4a2f-80c.iam.gserviceaccount.com
      containers:
        - image: asia-southeast1-docker.pkg.dev/project-51769b5e-7f0f-4a2f-80c/meetchi/meetchi-gpu-asr:latest
          ports:
            - name: http1
              containerPort: 8080
          resources:
            limits:
              cpu: "8"
              memory: 32Gi
              nvidia.com/gpu: "1"
          env:
            - name: DATABASE_URL
              value: "sqlite:////mnt/gcs/db/meetchi.db"
            - name: PYTHONPATH
              value: "/app"
            - name: HF_AUTH_TOKEN
              value: ""
          startupProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 20
            failureThreshold: 10
            timeoutSeconds: 10
          livenessProbe:
            httpGet:
              path: /health
              port: 8080
            periodSeconds: 60
            failureThreshold: 3
          volumeMounts:
            - name: gcs-data
              mountPath: /mnt/gcs
      volumes:
        - name: gcs-data
          csi:
            driver: gcsfuse.run.googleapis.com
            volumeAttributes:
              bucketName: project-51769b5e-7f0f-4a2f-80c-meetchi-audio
      nodeSelector:
        run.googleapis.com/accelerator: nvidia-l4
  traffic:
    - percent: 100
      latestRevision: true
